package br.com.zup.hellozupper.utils

const val USER_KEY = "user"
const val NAME_ERROR_MESSAGE = "Favor informar nome"
const val EMAIL_ERROR_MESSAGE = "Favor informar email"
const val PASSWORD_ERROR_MESSAGE = "Favor informar senha"
const val CREATE_USER_ERROR_MESSAGE = "Erro ao criar usuário!"
const val LOGIN_ERROR_MESSAGE = "Não foi possivel realizar o login!"
const val NAME_INCOMPLETE = "Favor o nome está incompleto"
const val PASSWORD_INCOMPLETE = "A senha informada deve ter no mínimo 6 caracteres"
const val EMAIL_INVALID = "E-mail inválido!"
const val HELLO = "Olá, "
const val ERRO_API_BENEFITS = "Não foi possível carregar a lista de benefícios"
const val BENEFITS = "Benefícios"
const val ERRO_API_PROGRAMS = "Não foi possível carregar a lista de programas"
const val PROGRAMS_KEY = "Chave programas"
const val PROGRAMAS = "Programas"
const val ERRO_API_PILLARS = "Não foi possível carregar a lista de pilares"
const val NOSSO_DNA = "Nosso DNA"
const val KEY_PILLAR = "Chave pillar"

